apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
  namespace: roboshop

spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: cache-volume

    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - mountPath: /mnt/nginx-log
          name: cache-volume

  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi