apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: roboshop
  project: frontend
  name: ebs-static-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-0032626534bc9574c   # 👈 your EBS volume ID
    fsType: ext4

---
#pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: roboshop
  project: frontend
  name: ebs-static-pv # this is name refer as the above pv name here
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual   # 👈 MUST match PV
  resources:
    requests:
      storage: 15Gi           # 👈 MUST match PV

---
# creating pod for mount to the pvc
apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  project: frontend
  name: ebs-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: ebs-volume
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b

  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: ebs-static-pv

---
# load balancer

apiVersion: v1
kind: Service
metadata:
  name: ebs-static-pv
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: frontend
  ports:
    - port: 80
      targetPort: 80