apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: roboshop
  name: ebs-static-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-0032626534bc9574c   # 👈 your EBS volume ID
    fsType: ext4