apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi   # dummy value (EFS unlimited)
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany   # 👈 important (multi-pod access)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c5ae73f7261404a8   # 👈 EFS ID


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
  namespace: roboshop
  labels:
    project: frontend
spec:
  accessModes:
    - ReadWriteMany   # 👈 must match PV
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
  namespace: roboshop
  labels:
    project: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: efs-volume

  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-static-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: efs-service
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: frontend
  ports:
    - port: 80
      targetPort: 80