# 🔹 ConfigMap (normal config)
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: roboshop
data:
  APP_NAME: "myapp"

---

# 🔹 Secret (sensitive data)
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: roboshop
type: Opaque
data:
  PASSWORD: YWRtaW4=   # base64 for "admin"

---

# 🔹 Pod (using both)
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME

        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD