apiVersion: v1
kind: Pod
metadata:
  name: frontend-labels
  namespace: roboshop
  labels:
    name: frontend
    environment: development
    project: roboshop
    component: frontend

spec:
  containers:
  - name: nginx
    image: nginx