apiVersion: v1
kind: pod
Metadata:
    name: frontend-labels
    labels:
      name: frontend
      namespace: roboshop
      environment: development
      project: roboshop
      component: frontend
  
  