apiVersion: v1
kind: Pod
metadata:
  name: errors
  namespace: roboshop
  labels:
    name: labels-errors
    component: error
    project: dev
    environment: dev

spec:
  containers:
  - name: nginx
    image: nginx