apiVersion: v1
kind: Service
metadata:
  name: service-node-port

spec:
  type: NodePort
  selector:
    name: roboshop
    project: frontend
    environment: dev
    new: nodeport

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80