apiVersion: v1
kind: Pod
metadata:
  name: Loadbalacer
  labels:
    name: roboshop
    project: frontend
    environment: dev
    new: nodeport
    latest: traffic

spec:
  containers:
    - name: nginx
      image: nginx