apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-demo   # Deployment name

spec:
  replicas: {{.Values.deployment.replica}}             # 3 pods kavali

  selector:
    matchLabels:
      app: helm-demo      # Deployment identifies pods

  template:
    metadata:
      labels:
        app: helm-demo    # Pod label (must match selector)

    spec:
      containers:
      - name: nginx
        image: {{.Values.deployment.imageVersion}}
        ports:
        - containerPort: 80