apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment   # Deployment name

spec:
  replicas: {{.Values.deployment.replica}}             # 3 pods kavali

  selector:
    matchLabels:
      app: nginx-demo      # Deployment identifies pods

  template:
    metadata:
      labels:
        app: nginx-demo    # Pod label (must match selector)

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80