apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: affinity-pod   # Pod name
spec:
  containers:
  - name: nginx        # Container name
    image: nginx       # Image

  affinity:
    nodeAffinity:

      # 🔴 REQUIRED (must match - compulsory)
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone   # 👈 NEW label (zone)
            operator: In                       # 👈 OR condition
            values:
            - us-east-1c                       # 👈 ee zone lo unna node lo ne run avvali

      # 🟡 PREFERRED (optional - best choice)
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1                              # 👈 priority
        preference:
          matchExpressions:
          - key: node.kubernetes.io/instance-type   # 👈 NEW label (instance type)
            operator: In
            values:
            - t2.medium                        # 👈 ee type node unte better