apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: roboshop
subjects:
- kind: User
  name: eswar-new-eks-readonly # Name of the user (case-sensitive)
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # Must be Role or ClusterRole
  name: pod-reader # Must match the name of the Role you created
  apiGroup: rbac.authorization.k8s.io
