apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::273354633043:role/eksctl-roboshop-dev-eks-addon-iamserviceaccou-Role1-4Orr68vRq7Iv
  creationTimestamp: "2026-03-20T13:34:46Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: my-service-account
  namespace: roboshop
  resourceVersion: "100538"
  uid: 7aad7e5b-240d-48d5-b8a2-62b5128ceda1
