apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::273354633043:role/eksctl-roboshop-dev-eks-nodegroup--NodeInstanceRole-mntP24cL5xYi
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::273354633043:user/todayuser
      username: todayuser
      groups:
        - readonly-group   # 👈 custom group