apiVersion: v1
kind: ConfigMap
data:
  mapRoles: |
    - rolearn: arn:aws:iam::273354633043:role/eksctl-roboshop-dev-eks-nodegroup--NodeInstanceRole-mntP24cL5xYi
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::273354633043:user/todayuser
      username: todayuser
      groups:
        - system:masters